### ISSUE TITLE
GA talk: Source Code Pro fails to load

### ISSUE THREAD

**Issue by myakura** [philipwalton/talks#2]
thanks! great talk.

i just noticed that https://github.com/philipwalton/talks/blob/eb3408d1b273a9508d74731f4d160baa5e5c89f6/2015-11-19/theme.css#L2 tries to load Source Code Pro but this'll fail due to mixed content blocking.

**Comment by philipwalton** [comment]
Thanks! I didn't notice because I was always running it locally.

Fixed via 99195f80bee17eaa98c5f98de08c58e1af1999ec.
